### PR TITLE
make quad stash behave like on the website

### PR DESCRIPTION
**Pull request by MarcLandis**

### CODE REVIEW

**Comment by MarcLandis** [comment]
this one needs rebase after #752 is merged

**Comment by aydjay** [comment]
To be honest I hate the way the stash control works in general - but your changes look fine by me.

**Comment by MarcLandis** [comment]
It would be cleaner if the quad stash would be completely separated from the normal stash.

**Comment by Stickymaddness** [comment]
@MarcLandis #752 has been merged

**Comment by MarcLandis** [comment]
this is now ready to be merged

**Comment by Stickymaddness** [comment]
I've just noticed some of the image replacements are incorrect, 

eg: blue-socketed-white.png was a blue socket containing a white gem but has been replaced with a white socket containing a blue gem.

**Comment by Stickymaddness** [comment]
@MarcLandis Would be great to have this merged, the white socket images just need to be fixed...

**Comment by MarcLandis** [comment]
I will work on this in the next few days. Too much real life and now 3.1 :)

**Comment by aydjay** [comment]
@MarcLandis If my abyssal support hasn't made it to master can you base your changes off mine?

**Comment by MarcLandis** [comment]
@aydjay all fixed and rebased

**Pull request merged**
