### PR TITLE
Adding Essences to currencies to reduce exceptions thrown by client.

### PR DESCRIPTION
**Pull request by aydjay**
Solves:
#650 

There are other that could be closed as it's not the only one.

I'm not sure that this is the best thing to do but there is a "Generator" for the essences so I hope people don't have to do it by hand.

### CODE REVIEW

**Comment by Stickymaddness** [comment]
Nice generator for the Essences, beats writing it out by hand 👍, however I have a few comments:

- Essences aren't currency, rather create a new type for Essences. ItemFactory can then return a new Essences (checking the typeline for "Essence Of" should suffice). That way the Essence class can be extended to contain other info, like the tier and type, which in turn means a filter can be written for them.

- The Essence generator does not need to be in the Currency class or even in the same solution. Rather create a separate tools solution of which the essence generator can be a part of.

**Comment by aydjay** [comment]
Tell me about the hand writting.....

I wasn't super happy about having the generator in the currency class but I wasn't sure where else to put it.

I'll take your comments onboard and I'll see where I get too with it.

**Comment by aydjay** [comment]
This will add essences as a type of their own as you have suggested.

The essence recipe needs to be added but I don't have sufficient essences in my stash to be able to test this adequately.

I'd like to tackle the recipe portion as a separate stream of work.

I had an exception thrown by the converter when hovering over the essences - i've handled it appropriately. The colour can be changed easily enough.

I added a "Stackable" item so that I didn't have any duplication.

**Comment by Stickymaddness** [comment]
Nice find with the NotImplementedException(), that's probably been sitting around in there since the beginning.

I will probably move the generation out, but for now will just merge. Nice work.

**Pull request merged**
