### PR TITLE
Synthesised League item properties

### PR DESCRIPTION
**Pull request by thailyn**
This PR adds support for synthesised and fractured item properties.  The synthesised property is a simple boolean, while the fractured property is a boolean along with a list of string mods.  These mods are displayed before any explicit mods on the item. (Any synthesised mods simply show up as implicit mods.)

Note: I do not have the icon adorners yet, as we've only seen them in screenshots so far (e.g., [synthesised](https://twitter.com/pathofexile/status/1103062985239552000/photo/1) and [fractured](https://twitter.com/pathofexile/status/1103022868982489094/photo/1)).  I'll add the image files for those icons once I get my hands on them.

#965

### CODE REVIEW

**Comment by aydjay** [comment]
From: https://www.pathofexile.com/forum/view-thread/2333648

Enchantments (such as those found from the Labyrinth) now have their own mod slot on items. They no longer use the Implicit mod slot.

**Comment by thailyn** [comment]
I can support for enchantments once we have a bit more information on them (e.g., what are the JSON properties named, where do they sit in the tooltip relative to implicit mods, what color to use?).

I've guessed the URL for the fractured symbol is https://web.poecdn.com/image/item/popup/fractured-symbol.png .  However, I haven't figured out the URL for the synthesised symbol yet.

**Comment by aydjay** [comment]
Oh for sure, was just a note so we remember :)

**Comment by Stickymaddness** [comment]
Was hoping to get this change in myself this week, but didn't get any time unfortunately. Thanks for getting on it.

Synthesis symbol is here: https://web.poecdn.com/image/item/popup/synthetic-symbol.png?1550034833000

**Comment by aydjay** [comment]
https://www.pathofexile.com/forum/view-thread/2333275

Sample Synthesised and Fractured json snippets are in this forum post. 

If you could add some Unit Tests that leverage these snippets that would be amazing!

**Comment by thailyn** [comment]
Thanks for finding the location of the synthesised icon!  I've added both icons and a unit test to parse the sample JSON.

**Pull request merged**
