### PR TITLE
How to get SessionID?

### PR DESCRIPTION
**Pull request by bule2015**
Added the image to jump to a page with instructions on how get the SessionID.

[https://gyazo.com/50e9d2069d67bce5247ddc240a92138e](https://gyazo.com/50e9d2069d67bce5247ddc240a92138e)

### CODE REVIEW

**Comment by Stickymaddness** [comment]
I like the idea of this, but the wiki article is _ancient_, I don't even think the cookie name it refers to is correct. In order to merge something like this there would need to be an up to date article on the github wiki that it links to.

**Comment by bule2015** [comment]
I expected that someone would correct wiki. 
Because I'm because there are no English abilities fatally.
But I'll try my best.

**Comment by bule2015** [comment]
How about with this?
https://github.com/bule2015/Procurement/wiki

**Comment by aydjay** [comment]
Looks good apart from the steam section - it reads a little bit like you can login to procurement with steam, which isn't the case.

I would write:

・Can I log in to pathofexile.com using my steam account?

　　Yes, Please login using "Sign in through STEAM". The POESESSID retrieval will be the same.

**Comment by bule2015** [comment]
It was rewritten as follows.

・Can Steam account also acquire SessionID?
　　Yes, When logging in by a official site, SessionID can be acquired.

**Comment by Stickymaddness** [comment]
I've copied your wiki page to https://github.com/Stickymaddness/Procurement/wiki/SessionID, if you link to it in your PR I can merge it.

**Pull request merged**
